name: Migrate Angular 5 to Angular 9

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Angular CLI v6
        run: |
          npm uninstall -g @angular/cli
          npm install -g @angular/cli@6

      - name: Update Angular Project to v6
        run: |
          npm install @angular/cli@6 @angular/core@6 @angular/compiler-cli@6 --save
          ng update @angular/cli
          npm install rxjs@6 rxjs-compat@6 --save
          npm install typescript@2.9 --save-dev
          npx rxjs-5-to-6-migrate -p src/tsconfig.app.json
          ng build --prod

      - name: Install Angular CLI v7
        run: |
          npm install -g @angular/cli@7

      - name: Update Angular Project to v7
        run: |
          ng update @angular/cli@7 @angular/core@7
          npm install typescript@3.1 --save-dev
          ng build --prod

      - name: Install Angular CLI v8
        run: |
          npm install -g @angular/cli@8

      - name: Update Angular Project to v8
        run: |
          ng update @angular/cli@8 @angular/core@8
          npm install typescript@3.4 --save-dev
          ng build --prod

      - name: Install Angular CLI v9
        run: |
          npm install -g @angular/cli@9

      - name: Update Angular Project to v9
        run: |
          ng update @angular/cli@9 @angular/core@9
          ng update @angular/core --migrate-only --from 8 --to 9
          npm prune
          npm audit fix
          ng build --prod

      - name: Test the Application
        run: |
          ng test --watch=false

      - name: Commit and Push Changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add .
          git commit -m "Migrated Angular 5 to Angular 9"
          git push origin main
